import { Resend } from 'resend';

/**
 * Send a digest or report via email using Resend
 */
export async function sendEmailReport(options: {
  to: string;
  subject: string;
  markdownContent: string;
}): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.log('[Email] RESEND_API_KEY not set, skipping email delivery.');
    return;
  }

  const resend = new Resend(apiKey);

  // Convert markdown to simple HTML
  const htmlContent = markdownToHtml(options.markdownContent);

  const { error } = await resend.emails.send({
    from: 'The Great Wall <noreply@updates.voyager.dev>',
    to: options.to,
    subject: options.subject,
    html: htmlContent,
  });

  if (error) {
    console.error('[Email] Failed to send:', error);
    throw new Error(`Email delivery failed: ${error.message}`);
  }

  console.log(`[Email] Report sent to ${options.to}`);
}

/**
 * Simple markdown to HTML conversion for email
 */
function markdownToHtml(md: string): string {
  let html = md
    // Headers
    .replace(/^### (.+)$/gm, '<h3 style="color:#D97706;margin:16px 0 8px">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#F59E0B;margin:20px 0 10px;border-bottom:1px solid #333;padding-bottom:4px">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="color:#FCD34D;margin:0 0 16px;font-size:24px">$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/_(.+?)_/g, '<em style="color:#9CA3AF">$1</em>')
    // Checkboxes
    .replace(/^- \[ \] (.+)$/gm, '<div style="margin:4px 0">☐ $1</div>')
    .replace(/^- \[x\] (.+)$/gm, '<div style="margin:4px 0">☑ $1</div>')
    // Bullet lists
    .replace(/^- (.+)$/gm, '<li style="margin:2px 0">$1</li>')
    // Numbered lists
    .replace(/^(\d+)\. (.+)$/gm, '<li style="margin:4px 0"><strong>$1.</strong> $2</li>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr style="border:1px solid #333;margin:16px 0">')
    // Code
    .replace(/`(.+?)`/g, '<code style="background:#1E293B;padding:2px 6px;border-radius:4px;font-size:13px">$1</code>')
    // Line breaks
    .replace(/\n\n/g, '</p><p style="margin:8px 0">')
    .replace(/\n/g, '<br>');

  return `
    <div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,monospace;max-width:700px;margin:0 auto;background:#0F172A;color:#E2E8F0;padding:32px;border-radius:12px;border:1px solid rgba(255,255,255,0.1)">
      <p style="margin:8px 0">${html}</p>
      <div style="margin-top:24px;padding-top:16px;border-top:1px solid #333;color:#64748B;font-size:12px">
        Generated by The Great Wall — AI Intelligence Perimeter
      </div>
    </div>
  `;
}
