import type { WatchmanItemAnalysis } from '../watchman/types.js';

/**
 * Generate an emergency alert markdown for items scoring >= 9.0
 */
export function generateEmergencyAlert(item: WatchmanItemAnalysis & { title: string; source_name: string }): string {
  const now = new Date().toISOString();

  const lines: string[] = [];

  lines.push(`# EMERGENCY: ${item.title}`);
  lines.push(`**Detected**: ${now}`);
  lines.push(`**Source**: ${item.source_name}`);
  lines.push(`**Composite Score**: ${item.composite_score?.toFixed(1)}/10`);
  lines.push(`**Confidence**: ${item.confidence}`);
  lines.push('');

  lines.push('## What Happened');
  lines.push(item.analysis);
  lines.push('');

  lines.push('## Scores');
  lines.push(`- Significance: ${item.significance_score}/10`);
  lines.push(`- Voyager Relevance: ${item.voyager_relevance_score}/10`);
  lines.push(`- Actionability: ${item.actionability_score}/10`);
  lines.push(`- Threat Level: ${item.threat_score}/10`);
  lines.push('');

  if (item.project_mappings.length > 0) {
    lines.push('## Affected Projects');
    for (const mapping of item.project_mappings) {
      lines.push(`- **${mapping.project}** (relevance: ${mapping.relevance}/10)`);
      lines.push(`  Action: ${mapping.action}`);
    }
    lines.push('');
  }

  lines.push('## Immediate Actions');
  if (item.project_mappings.length > 0) {
    for (const mapping of item.project_mappings) {
      lines.push(`- [ ] ${mapping.action} [${mapping.project}]`);
    }
  } else {
    lines.push('- [ ] Review this development and assess impact');
  }

  lines.push('');
  lines.push('---');
  lines.push(`_Generated by The Great Wall — Emergency Alert System_`);

  return lines.join('\n');
}
